export const syllabus = [
  {
    subject: "Biology",
    topics: [
      "Cell Biology",
      "Biochemistry",
      "Genetics",
      "Molecular Biology",
      "Evolution",
      "Microbiology",
      "Plant Biology",
      "Animal Biology",
      "Ecology",
      "Biotechnology",
      "Methods in Biology",
      "Molecular biology techniques",
    ],
  },
  {
    subject: "Chemistry",
    topics: [
      "Structure and properties of Atoms",
      "Chemical kinetics, thermodynamics, and equilibrium",
      "Chemistry of organic compounds",
      "Instrumental techniques",
    ],
  },
  {
    subject: "Mathematics",
    topics: [
      "Sets, Relations and Functions",
      "Mathematical Induction",
      "Complex numbers",
      "Linear and Quadratic equations",
      "Sequences and Series",
      "Cartesian System of Rectangular Coordinates",
      "Three-Dimensional Geometry",
      "Permutations and Combinations",
      "Binomial Theorem",
      "Matrices and Determinants",
      "Limits and Continuity",
      "Differentiation and Integration",
      "Probability and Statistics",
    ],
  },
  {
    subject: "Physics",
    topics: [
      "Motion in one and two dimensions",
      "Laws of motion",
      "Conservation of energy",
      "System of particles and rotational motion",
      "Thermal properties of matter",
      "Heat and laws of thermodynamics",
      "Kinetic theory of gases",
    ],
  },
];
